version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.1-node-browsers
        environment:
          RACK_ENV: test
      - image: circleci/node:7.10
      - image: circleci/postgres:9.6.5
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: where-is-grey-test

    working_directory: ~/where-is-grey

    steps:
      - checkout

      ################
      # Dependencies #
      ################
      - restore_cache:
          key: v1-ruby-dependencies-{{ checksum "Gemfile.lock" }}
      - restore_cache:
          key: v1-node-dependencies-{{ checksum "package.json" }}
      - run:
          name: Installing Ruby dependencies
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run:
          name: Installing Node dependencies
          command: npm install
      - save_cache:
          key: v1-ruby-dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/where-is-grey/vendor/bundle
      - save_cache:
          key: v1-node-dependencies-{{ checksum "package.json" }}
          paths:
            - ~/where-is-grey/node_modules
      - run:
          name: Installing latest postgresql-client
          command: sudo apt-get update && sudo apt install -y postgresql-client-9.6 || true

      #########################
      # Environment variables #
      #########################
      - run:
          name: Setting environment variables
          command: cp dummy-env .env

      ############
      # Database #
      ############
      - run:
          name: Creating database
          command: bundle exec rake db:create db:structure:load
          environment:
            DATABASE_URL: postgres://circleci:@127.0.0.1:5432/where-is-grey-test

      #########
      # Tests #
      #########
      - run:
          name: Running tests
          command: bundle exec rspec spec
