on:
  push:
  schedule:
    # At 01:00.
    - cron:  '0 1 * * *'

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan website
    steps:
      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'https://whereis.greysteil.com/'
          rules_file_name: '.github/workflows/zap-scan-rules.tsv'
